import 'growth_reward_repository.dart';

const avatarRewardItems = <UnlockableItem>[
  UnlockableItem(
    id: 'bathroom_soap_01',
    name: '초록 비누',
    type: UnlockableItemType.spaceItem,
    category: 'bathroom',
    icon: '🧼',
    spaceId: 'bathroom',
  ),
  UnlockableItem(
    id: 'bathroom_towel_01',
    name: '노란 수건',
    type: UnlockableItemType.spaceItem,
    category: 'bathroom',
    icon: '🧺',
    spaceId: 'bathroom',
  ),
  UnlockableItem(
    id: 'bathroom_toothbrush_01',
    name: '칫솔과 치약',
    type: UnlockableItemType.spaceItem,
    category: 'bathroom',
    icon: '🪥',
    spaceId: 'bathroom',
  ),
  UnlockableItem(
    id: 'bathroom_shampoo_01',
    name: '샴푸',
    type: UnlockableItemType.spaceItem,
    category: 'bathroom',
    icon: '🧴',
    spaceId: 'bathroom',
  ),
  UnlockableItem(
    id: 'bedroom_rack_01',
    name: '옷걸이',
    type: UnlockableItemType.spaceItem,
    category: 'bedroom',
    icon: '🧥',
    spaceId: 'bedroom',
  ),
  UnlockableItem(
    id: 'bedroom_basket_01',
    name: '옷 바구니',
    type: UnlockableItemType.spaceItem,
    category: 'bedroom',
    icon: '🧺',
    spaceId: 'bedroom',
  ),
  UnlockableItem(
    id: 'bedroom_folded_01',
    name: '개어 놓은 옷',
    type: UnlockableItemType.spaceItem,
    category: 'bedroom',
    icon: '👕',
    spaceId: 'bedroom',
  ),
  UnlockableItem(
    id: 'bedroom_hat_01',
    name: '노란 모자',
    type: UnlockableItemType.spaceItem,
    category: 'bedroom',
    icon: '🧢',
    spaceId: 'bedroom',
  ),
  UnlockableItem(
    id: 'kitchen_cup_01',
    name: '초록 컵',
    type: UnlockableItemType.spaceItem,
    category: 'kitchen',
    icon: '🥤',
    spaceId: 'kitchen',
  ),
  UnlockableItem(
    id: 'kitchen_cutlery_01',
    name: '수저 세트',
    type: UnlockableItemType.spaceItem,
    category: 'kitchen',
    icon: '🥄',
    spaceId: 'kitchen',
  ),
  UnlockableItem(
    id: 'kitchen_dishes_01',
    name: '그릇 세트',
    type: UnlockableItemType.spaceItem,
    category: 'kitchen',
    icon: '🍽️',
    spaceId: 'kitchen',
  ),
  UnlockableItem(
    id: 'kitchen_cloth_01',
    name: '닦는 천',
    type: UnlockableItemType.spaceItem,
    category: 'kitchen',
    icon: '🧽',
    spaceId: 'kitchen',
  ),
  UnlockableItem(
    id: 'playroom_toybox_01',
    name: '장난감 상자',
    type: UnlockableItemType.spaceItem,
    category: 'playroom',
    icon: '🧸',
    spaceId: 'playroom',
  ),
  UnlockableItem(
    id: 'playroom_shelf_01',
    name: '작은 책장',
    type: UnlockableItemType.spaceItem,
    category: 'playroom',
    icon: '📚',
    spaceId: 'playroom',
  ),
  UnlockableItem(
    id: 'playroom_laundry_01',
    name: '빨래 바구니',
    type: UnlockableItemType.spaceItem,
    category: 'playroom',
    icon: '🧺',
    spaceId: 'playroom',
  ),
  UnlockableItem(
    id: 'playroom_trash_01',
    name: '초록 휴지통',
    type: UnlockableItemType.spaceItem,
    category: 'playroom',
    icon: '🗑️',
    spaceId: 'playroom',
  ),
  UnlockableItem(
    id: 'entrance_bag_01',
    name: '외출 가방',
    type: UnlockableItemType.spaceItem,
    category: 'entrance',
    icon: '🎒',
    spaceId: 'entrance',
  ),
  UnlockableItem(
    id: 'entrance_bottle_01',
    name: '물병',
    type: UnlockableItemType.spaceItem,
    category: 'entrance',
    icon: '🧴',
    spaceId: 'entrance',
  ),
  UnlockableItem(
    id: 'entrance_wipes_01',
    name: '손수건과 물티슈',
    type: UnlockableItemType.spaceItem,
    category: 'entrance',
    icon: '🧻',
    spaceId: 'entrance',
  ),
  UnlockableItem(
    id: 'entrance_umbrella_01',
    name: '노란 우산',
    type: UnlockableItemType.spaceItem,
    category: 'entrance',
    icon: '☂️',
    spaceId: 'entrance',
  ),
  UnlockableItem(
    id: 'safety_cone_01',
    name: '안전 원뿔',
    type: UnlockableItemType.spaceItem,
    category: 'safety',
    icon: '🚧',
    spaceId: 'safety',
  ),
  UnlockableItem(
    id: 'safety_stop_01',
    name: '멈춤 표지',
    type: UnlockableItemType.spaceItem,
    category: 'safety',
    icon: '🛑',
    spaceId: 'safety',
  ),
  UnlockableItem(
    id: 'safety_crosswalk_01',
    name: '횡단보도 매트',
    type: UnlockableItemType.spaceItem,
    category: 'safety',
    icon: '🚸',
    spaceId: 'safety',
  ),
  UnlockableItem(
    id: 'safety_contact_01',
    name: '도움 카드',
    type: UnlockableItemType.spaceItem,
    category: 'safety',
    icon: '☎️',
    spaceId: 'safety',
  ),
  UnlockableItem(
    id: 'avatar_top_01',
    name: '파란 윗옷',
    type: UnlockableItemType.avatarItem,
    category: 'top',
    icon: '👕',
    spaceId: null,
  ),
  UnlockableItem(
    id: 'avatar_bottom_01',
    name: '편한 바지',
    type: UnlockableItemType.avatarItem,
    category: 'bottom',
    icon: '🩳',
    spaceId: null,
  ),
  UnlockableItem(
    id: 'avatar_shoes_01',
    name: '운동화',
    type: UnlockableItemType.avatarItem,
    category: 'shoes',
    icon: '👟',
    spaceId: null,
  ),
  UnlockableItem(
    id: 'avatar_hat_01',
    name: '노란 모자',
    type: UnlockableItemType.avatarItem,
    category: 'hat',
    icon: '🧢',
    spaceId: null,
  ),
  UnlockableItem(
    id: 'avatar_accessory_01',
    name: '외출 가방',
    type: UnlockableItemType.avatarItem,
    category: 'accessory',
    icon: '🎒',
    spaceId: null,
  ),
];

const avatarRewardByCardId = <String, String>{
  'H-01': 'bathroom_soap_01',
  'H-02': 'bathroom_soap_01',
  'H-03': 'bathroom_toothbrush_01',
  'H-04': 'bathroom_towel_01',
  'H-05': 'bathroom_shampoo_01',
  'H-06': 'bathroom_shampoo_01',
  'H-07': 'bathroom_soap_01',
  'H-08': 'bathroom_towel_01',
  'C-01': 'avatar_top_01',
  'C-02': 'avatar_bottom_01',
  'C-03': 'avatar_shoes_01',
  'C-04': 'avatar_shoes_01',
  'C-05': 'bedroom_rack_01',
  'C-06': 'bedroom_rack_01',
  'C-07': 'bedroom_basket_01',
  'C-08': 'bedroom_basket_01',
  'C-09': 'avatar_top_01',
  'C-10': 'bedroom_rack_01',
  'C-11': 'bedroom_basket_01',
  'C-12': 'bedroom_folded_01',
  'C-13': 'bedroom_hat_01',
  'M-01': 'kitchen_cup_01',
  'M-02': 'kitchen_cutlery_01',
  'M-03': 'kitchen_dishes_01',
  'M-04': 'kitchen_dishes_01',
  'M-05': 'kitchen_cloth_01',
  'B-04': 'kitchen_cloth_01',
  'B-01': 'playroom_shelf_01',
  'B-02': 'playroom_toybox_01',
  'B-03': 'playroom_laundry_01',
  'B-05': 'playroom_laundry_01',
  'B-06': 'playroom_shelf_01',
  'B-07': 'playroom_shelf_01',
  'B-08': 'playroom_shelf_01',
  'B-09': 'playroom_toybox_01',
  'B-10': 'playroom_trash_01',
  'B-11': 'playroom_laundry_01',
  'O-01': 'avatar_hat_01',
  'O-02': 'entrance_bag_01',
  'O-03': 'entrance_bag_01',
  'O-04': 'entrance_wipes_01',
  'O-05': 'entrance_bottle_01',
  'O-06': 'entrance_wipes_01',
  'O-07': 'bedroom_rack_01',
  'O-08': 'avatar_accessory_01',
  'O-09': 'entrance_bottle_01',
  'O-10': 'entrance_umbrella_01',
  'O-11': 'avatar_hat_01',
  'O-12': 'bedroom_rack_01',
  'S-01': 'safety_stop_01',
  'S-02': 'safety_crosswalk_01',
  'S-03': 'safety_cone_01',
  'S-04': 'safety_contact_01',
  'S-05': 'safety_contact_01',
  'T-01': 'bathroom_towel_01',
  'T-02': 'bathroom_soap_01',
  'T-03': 'bedroom_basket_01',
  'T-04': 'bedroom_basket_01',
  'T-05': 'bathroom_towel_01',
  'T-06': 'bathroom_soap_01',
  'T-07': 'bedroom_folded_01',
};
